# Generated by Django 2.2.22 on 2021-05-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200, verbose_name='Название товара')),
                ('product_description', models.TextField(verbose_name='Описание товара')),
                ('product_price', models.FloatField(verbose_name='Цена товара')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации товара')),
            ],
        ),
    ]
