# Generated by Django 2.2.22 on 2021-05-08 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210508_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processor_title', models.CharField(max_length=200, verbose_name='Название процессора')),
                ('processor_description', models.TextField(verbose_name='Описание процессора')),
            ],
            options={
                'verbose_name': 'Процессор',
                'verbose_name_plural': 'Процессоры',
            },
        ),
        migrations.CreateModel(
            name='Videocard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videocard_title', models.CharField(max_length=200, verbose_name='Название видеокарты')),
                ('videocard_description', models.TextField(verbose_name='Описание видеокарты')),
            ],
            options={
                'verbose_name': 'Видеокарта',
                'verbose_name_plural': 'Видеокарты',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_ram',
            field=models.FloatField(default=1, verbose_name='Постоянная память'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='product_rom',
            field=models.FloatField(default=1, verbose_name='Оперативная память'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='processor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Processor'),
            preserve_default=False,
        ),
    ]
