# Generated by Django 2.2.22 on 2021-05-09 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210509_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='videocard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.Videocard'),
            preserve_default=False,
        ),
    ]
